version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///./well_data.db

  db:
    image: sqlite:latest
    volumes:
      - ./well_data.db:/well_data.db