"""Пересоздание таблицы well с уникальным ограничением на id_well и id_tag

Revision ID: 8e9c17260688
Revises: 28335db6510b
Create Date: 2025-02-17 13:39:50.444320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9c17260688'
down_revision: Union[str, None] = '28335db6510b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
