"""Добавлено уникальное ограничение на id_well и id_tag

Revision ID: 9fdacf59bb28
Revises: 
Create Date: 2025-02-17 12:50:41.749361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdacf59bb28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_well', sa.Integer(), nullable=True),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.Column('tag_val', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_well', 'id_tag', name='uix_id_well_id_tag')
    )
    op.create_index(op.f('ix_well_date_time'), 'well', ['date_time'], unique=False)
    op.create_index(op.f('ix_well_id'), 'well', ['id'], unique=False)
    op.create_index(op.f('ix_well_id_tag'), 'well', ['id_tag'], unique=False)
    op.create_index(op.f('ix_well_id_well'), 'well', ['id_well'], unique=False)
    op.create_index(op.f('ix_well_tag_val'), 'well', ['tag_val'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_well_tag_val'), table_name='well')
    op.drop_index(op.f('ix_well_id_well'), table_name='well')
    op.drop_index(op.f('ix_well_id_tag'), table_name='well')
    op.drop_index(op.f('ix_well_id'), table_name='well')
    op.drop_index(op.f('ix_well_date_time'), table_name='well')
    op.drop_table('well')
    # ### end Alembic commands ###
